#include "Constant.hpp"
#include <iostream>

const std::string fantasticIdeas[100] = {
	"Start a gratitude journal",
	"Read a book every month",
	"Plan a trip to a place you've never been",
	"Try cooking a new recipe every week",
	"Learn a new language",
	"Visit a museum or art exhibit",
	"Take a walk in nature",
	"Volunteer for a cause you care about",
	"Start a hobby you've always wanted to try",
	"Spend time with loved ones",
	"Plan a picnic in the park",
	"Take a yoga or meditation class",
	"Plant a garden",
	"Take up a sport or physical activity",
	"Learn to play a musical instrument",
	"Write letters to friends and family",
	"Try a new type of cuisine",
	"Learn about a new topic or subject",
	"Practice mindfulness or meditation",
	"Start a DIY home improvement project",
	"Explore your city or town",
	"Take a pottery or art class",
	"Join a local club or group",
	"Learn to bake or cook a special dish",
	"Spend a day at the spa or wellness retreat",
	"Go hiking or camping",
	"Start a book club",
	"Attend a live concert or theater performance",
	"Start a collection (coins, stamps, etc.)",
	"Take a dance class",
	"Spend time with pets or consider adopting one",
	"Go on a scenic drive or road trip",
	"Take up photography",
	"Listen to podcasts or audio books",
	"Spend a day unplugged from technology",
	"Write a poem or short story",
	"Try stargazing or astronomy",
	"Go on a bike ride",
	"Spend a day exploring a nearby city or town",
	"Take a painting or drawing class",
	"Try bird watching",
	"Visit a farmer's market or local food festival",
	"Start a fitness challenge",
	"Learn about your family history or genealogy",
	"Write a bucket list",
	"Create a piece of art or craft",
	"Go for a swim in a lake or ocean",
	"Try a new coffee shop or bakery",
	"Join a gym or fitness class",
	"Host a movie night with friends",
	"Try a new form of exercise like pilates or tai chi",
	"Plan a surprise party for a loved one",
	"Learn to make homemade candles or soap",
	"Take a cooking class or workshop",
	"Go to a wine tasting",
	"Learn about different types of tea",
	"Try journaling or writing",
	"Explore different cultures through food or books",
	"Take a scenic hike or nature walk",
	"Take a floral arrangement or gardening class",
	"Start a scrapbooking project",
	"Host a themed dinner party",
	"Watch a documentary about a subject you're interested in",
	"Go to a local fair or festival",
	"Try making homemade ice cream or desserts",
	"Plan a game night with friends",
	"Go to an amusement park or fun fair",
	"Take a sailing or water sports class",
	"Visit a zoo or animal sanctuary",
	"Host a potluck dinner",
	"Join a volunteer group or charity",
	"Go to a comedy club or show",
	"Visit a botanical garden or nature reserve",
	"Plan a beach day with friends and family",
	"Go to a local sports event",
	"Start a blog or YouTube channel",
	"Plan a cabin or cottage getaway",
	"Try a new type of workout class",
	"Plan a camping trip with friends",
	"Learn to make jewelry or other crafts",
	"Visit a historic site or landmark",
	"Start a home decor project",
	"Try making your own clothes or costumes",
	"Take a mixology or wine-making class",
	"Learn to write calligraphy or do hand-lettering",
	"Start a vegetable or herb garden",
	"Plan a treasure hunt for kids or friends",
	"Learn to make your own beauty or skincare products",
	"Join a choir or local theater group",
	"Take a coding or programming class",
	"Visit a trampoline park or fun center",
	"Start a podcast about a topic you're passionate about",
	"Go to a drive-in movie theater",
	"Try out a new board game or card game",
	"Learn a magic trick or juggling",
	"Host a backyard barbecue or cookout",
	"Start a DIY furniture project",
	"Take a martial arts or self-defense class",
	"Go to a poetry reading or literature festival",
	"Start a meditation or mindfulness practice",
};

const std::string sillyIdeas[100] = {
	"Invent a water-proof towel",
	"Solar-powered flashlight",
	"Glow-in-the-dark sunglasses",
	"Inflatable dart boards",
	"Ejector seats for helicopters",
	"Fireproof matches",
	"Waterproof tea bags",
	"Silent alarm clock",
	"Dehydrated water in a can",
	"Reusable ice cubes",
	"Wooden frying pan",
	"One-sided dice",
	"Non-stick Cellotape",
	"Battery-powered battery charger",
	"Invisible ink highlighters",
	"Soundproof headphones",
	"Self-cleaning dirt",
	"Pedal-powered wheelchair",
	"Braille driving manual",
	"Screen doors for submarines",
	"Left-handed screw drivers",
	"An ashtray for motorbikes",
	"An inflatable anchor",
	"Glasses to help dogs see color",
	"Cordless bungee jump",
	"Bubblewrap popping simulator",
	"Inflatable dartboard",
	"Waterproof sponge",
	"Submarine with a sunroof",
	"Underwater hairdryer",
	"An umbrella with holes for better view",
	"Silent karaoke machine",
	"Transparent ink",
	"Treadmill for a desk chair",
	"Sandpaper toilet paper",
	"Self-destructing DVDs",
	"Brick lifejacket",
	"Microwave safe aluminum foil",
	"Shoes with reverse soles for backwards footprints",
	"Night vision sunglasses",
	"LED flashlight for solar powered devices",
	"Dehydrated water packets",
	"DVD Rewinder",
	"AC adapter for Solar powered calculators",
	"Helicopter Ejector Seat",
	"Training wheels for motorcycles",
	"Black highlighters",
	"Inflatable Thumbs for hitchhikers",
	"Hand-free toothpaste dispenser",
	"Solar powered night light",
	"Air conditioned motorcycle",
	"Pedal powered wheel chair",
	"Waterproof teabags",
	"Seatbelts for Motorbikes",
	"Wooden barbeque",
	"Helicopter with a convertible top",
	"Chocolate teapot",
	"Waterproof towel",
	"Fireproof matches",
	"Seatbelts for Motorbikes",
	"Paper towel made of glass",
	"Solar powered torch",
	"Folding water bed",
	"Glass hammer",
	"Chocolate fireplace",
	"Rubber nails",
	"Inflatable concrete",
	"Garden pond submarine",
	"Paper wine flask",
	"Cardboard oven",
	"Leather gardening gloves",
	"Glass nail file",
	"Waterproof teapot",
	"Strawberry scented poison ivy",
	"Bubblewrap with unpoppable bubbles",
	"Silent musical instruments",
	"Bread gloves",
	"Sundial wristwatch",
	"Umbrella with built-in rain collector",
	"Treadmill-powered computer charger",
	"Soundproof speaker",
	"Inflatable bird feeder",
	"Tapeless tape dispenser",
	"Cordless power cord",
	"Weightless dumbbells",
	"Leakproof sieve",
	"Instant water - just add water!",
	"Edible dish soap",
	"See-through curtains",
	"Non-sticky glue",
	"Porous umbrella",
	"Sugar-coated toothpaste",
	"Non-wetting water",
	"Lactose-free dairy creamer",
	"Unlosable lottery ticket",
	"Invisible clothing",
	"Self-cleaning dishes",
	"Wrinkle-free prune",
	"Self-sharpening pencil",
	"Invisible graffiti paint"
};
